# Generated by Django 3.0.3 on 2020-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200403_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynoparameters',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Visible entry?'),
        ),
        migrations.AddField(
            model_name='dynoparameters',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='finalinfo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Visible entry?'),
        ),
        migrations.AddField(
            model_name='finalinfo',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='fuelinfo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Visible entry?'),
        ),
        migrations.AddField(
            model_name='fuelinfo',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='requester',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Visible entry?'),
        ),
        migrations.AddField(
            model_name='requester',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Visible entry?'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='r_phone',
            field=models.CharField(max_length=12, verbose_name="Requester's phone number"),
        ),
        migrations.AlterField(
            model_name='requester',
            name='t_phone',
            field=models.CharField(max_length=12, verbose_name="Tester's phone number"),
        ),
    ]
