# Generated by Django 3.0.3 on 2020-04-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200407_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Requester'),
            preserve_default=False,
        ),
    ]
