# Generated by Django 3.0.3 on 2020-04-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_vehicle_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='backend.Requester'),
        ),
    ]
