# Generated by Django 3.0.3 on 2020-04-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200407_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='requester',
        ),
        migrations.CreateModel(
            name='DataHandler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('emissions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emissions', to='backend.Emissions')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requester', to='backend.Requester')),
                ('road_load', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='road_load', to='backend.RoadLoad')),
                ('soak_tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='soak_tag', to='backend.SoakTag')),
                ('vehicle_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle_info', to='backend.VehicleInfo')),
            ],
        ),
    ]
