# Generated by Django 3.0.3 on 2020-04-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200407_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='deleted_at',
            field=models.DateField(blank=True, verbose_name='Entry soft-delete date'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='deleted_at',
            field=models.DateField(blank=True, verbose_name='Entry soft-delete date'),
        ),
        migrations.AlterField(
            model_name='roadload',
            name='deleted_at',
            field=models.DateField(blank=True, verbose_name='Entry soft-delete date'),
        ),
        migrations.AlterField(
            model_name='soaktag',
            name='deleted_at',
            field=models.DateField(blank=True, verbose_name='Entry soft-delete date'),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='deleted_at',
            field=models.DateField(blank=True, verbose_name='Entry soft-delete date'),
        ),
    ]
