# Generated by Django 3.0.3 on 2020-04-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200407_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadload',
            name='coeff1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Target coeff A'),
        ),
        migrations.AlterField(
            model_name='roadload',
            name='coeff2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Target coeff B'),
        ),
        migrations.AlterField(
            model_name='roadload',
            name='coeff3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Target coeff C'),
        ),
    ]
