# Generated by Django 3.0.3 on 2020-04-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200407_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='marmon',
            field=models.DecimalField(choices=[('2', '2'), ('2.5', '2.5'), ('3', '3'), ('4', '4')], decimal_places=1, max_digits=2, verbose_name='Marmon flange size'),
        ),
    ]
