# Generated by Django 3.0.3 on 2020-04-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200407_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='marmon',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Marmon flange size'),
        ),
    ]
