# Generated by Django 3.0.3 on 2020-04-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200407_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='r_mobile',
            field=models.CharField(blank=True, max_length=12, verbose_name="Requester's mobile (if different)"),
        ),
    ]
