# Generated by Django 3.0.3 on 2020-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200428_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Entry soft-delete date'),
        ),
    ]
