# Generated by Django 3.0.3 on 2020-05-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200506_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Entry soft-delete date'),
        ),
        migrations.AlterField(
            model_name='roadload',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Entry soft-delete date'),
        ),
        migrations.AlterField(
            model_name='roadload',
            name='dyno_roll',
            field=models.CharField(choices=[('FWD', 'Fwd'), ('RWD', 'Rwd'), ('4WD', 'Awd')], max_length=3, verbose_name='Dyno roll configuration'),
        ),
        migrations.AlterField(
            model_name='soaktag',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Entry soft-delete date'),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Entry soft-delete date'),
        ),
    ]
