# Generated by Django 3.0.6 on 2020-05-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20200507_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahandler',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Visible entry?'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User who deleted the entry'),
        ),
    ]
