# Generated by Django 3.0.6 on 2020-06-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
