# Generated by Django 3.0.6 on 2020-06-02 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0011_update_proxy_permissions'),
        ('knox', '0007_auto_20190111_0542'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0022_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='User',
        ),
    ]
