# Generated by Django 3.0.7 on 2020-07-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20200709_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissions',
            name='cscm',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='CSCm Distance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadload',
            name='country',
            field=models.CharField(choices=[('US', 'Us'), ('USM', 'US Metric'), ('EU', 'Eu'), ('GTR', 'GTR 15'), ('1015', 'Japan 1015'), ('JC08', 'Japan JC08')], default='US', max_length=10, verbose_name='Country selection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadload',
            name='inertia',
            field=models.BooleanField(default=0, verbose_name='Inertia table lookup?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadload',
            name='mass_usa',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Mass (EPA)'),
            preserve_default=False,
        ),
    ]
