# Generated by Django 3.0.7 on 2020-09-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20200918_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='marmon_distance',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Dual flange distance'),
        ),
    ]
