# Generated by Django 3.0.7 on 2020-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20200918_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='marmon_distance',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dual flange distance'),
        ),
    ]
