# Generated by Django 3.0.7 on 2020-09-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20200918_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadload',
            name='coeff1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='Target coeff A'),
        ),
        migrations.AlterField(
            model_name='roadload',
            name='coeff2',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, verbose_name='Target coeff B'),
        ),
        migrations.AlterField(
            model_name='roadload',
            name='coeff3',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, verbose_name='Target coeff C'),
        ),
    ]
