# Generated by Django 3.0.7 on 2020-09-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auto_20200918_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soaktag',
            name='f_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Front tire pressure'),
        ),
        migrations.AlterField(
            model_name='soaktag',
            name='r_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Rear tire pressure'),
        ),
    ]
