# Generated by Django 3.0.7 on 2020-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20200922_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='cert_level',
            field=models.CharField(blank=True, choices=[('bin2', 'EPA Tier 2 Bin 2 (2004)'), ('bin3', 'EPA Tier 2 Bin 3 (2004)'), ('bin4', 'EPA Tier 2 Bin 4 (2004)'), ('bin5', 'EPA Tier 2 Bin 5 (2004)'), ('bin5_int', 'EPA Tier 2 Bin 5 Int (2004)'), ('bin6', 'EPA Tier 2 Bin 6 (2004)'), ('bin6_int', 'EPA Tier 2 Bin 6 Int (2004)'), ('bin7', 'EPA Tier 2 Bin 7 (2004)'), ('bin7_int', 'EPA Tier 2 Bin 7 Int (2004)'), ('bin8', 'EPA Tier 2 Bin 8 (2004)'), ('bin8_int', 'EPA Tier 2 Bin 8 Int'), ('bin20', 'EPA Tier 3 Bin 20 (2017)'), ('bin30', 'EPA Tier 3 Bin 30 (2017)'), ('bin50', 'EPA Tier 3 Bin 50 (2017)'), ('bin70', 'EPA Tier 3 Bin 70 (2017)'), ('bin125', 'EPA Tier 3 Bin 125 (2017)'), ('bin160', 'EPA Tier 3 Bin 160 (2017)'), ('e3_cl_m1', 'Cl Class M1 (2000)'), ('e3_cl_n1_1', 'CL Class N1_I (2000)'), ('e3_cl_n1_2', 'CL Class N1_II (2000)'), ('e3_cl_n1_3', 'CL Class N1_III (2000)'), ('e3_pl_m1', 'Pl Class M1 (2000)'), ('e3_pl_n1_1', 'PL Class N1_I (2000)'), ('e3_pl_n1_2', 'PL Class N1_II (2000)'), ('e3_pl_n1_3', 'PL Class N1_III (2000)'), ('e4_cl_m1', 'Cl Class M1 (2005)'), ('e4_cl_n1_1', 'CL Class N1_I (2005)'), ('e4_cl_n1_2', 'CL Class N1_II (2005)'), ('e4_cl_n1_3', 'CL Class N1_III (2005)'), ('e4_pl_m1', 'PL Class M1 (2005)'), ('e4_pl_n1_1', 'PL Class N1_I (2005)'), ('e4_pl_n1_2', 'PL Class N1_II (2005)'), ('e4_pl_n1_3', 'PL Class N1_III (2005)'), ('5a_cl_mn1_1', '5a Cl Class M N1_I (2009)'), ('5a_cl_n1_2', '5a CL Class N1_II (2009)'), ('5a_cl_n1_3_n2', '5a CL Class N1_III N2 (2009)'), ('5a_sl_mn1_1', '5a Sl Class M N1_I (2009)'), ('5a_sl_n1_2', '5a SL Class N1_II (2009)'), ('5a_sl_n1_3_n2', '5a SL Class N1_III N2 (2009)'), ('5b_cl_mn1_1', '5b Cl Class M N1_I (2011)'), ('5b_cl_n1_2', '5b CL Class N1_II (2011)'), ('5b_cl_n1_3_n2', '5b CL Class N1_III N2 (2011)'), ('5b_sl_mn1_1', '5b Sl Class M N1_I (2011)'), ('5b_sl_n1_2', '5b SL Class N1_II (2011)'), ('5b_sl_n1_3_n2', '5b SL Class N1_III N2 (2011)'), ('6a_cl_mn1_1', '6a Cl Class M N1_I (2014)'), ('6a_cl_n1_2', '6a CL Class N1_II (2014)'), ('6a_cl_n1_3_n2', '6a CL Class N1_III N2 (2014)'), ('6a_sl_mn1_1', '6a Sl Class M N1_I (2014)'), ('6a_sl_n1_2', '6a SL Class N1_II (2014)'), ('6a_sl_n1_3_n2', '6a SL Class N1_III N2 (2014)')], max_length=15, verbose_name='Certification'),
        ),
    ]
