# Generated by Django 3.0.7 on 2020-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20200922_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='regulation',
            field=models.CharField(blank=True, choices=[('86', 'CFR 86'), ('1066', 'CFR 1066'), ('E3', 'Euro 3 (2000)'), ('E4', 'Euro 4 (2005)'), ('E5', 'Euro 5 (2009)'), ('E6b', 'Euro 6b (2014)'), ('E6c', 'Euro 6c'), ('E6d_T', 'Euro 6d TEMP (2017)'), ('E6d', 'Euro 6d (2020)'), ('None', 'None')], max_length=5, verbose_name='Regulation'),
        ),
        migrations.AlterField(
            model_name='roadload',
            name='dyno_mode',
            field=models.CharField(blank=True, choices=[('Procedure', 'Yes, procedure attached'), ('Delivered', 'Yes, as delivered'), ('No', 'No'), ('None', 'None')], default='No', max_length=10, verbose_name='Dyno mode?'),
        ),
    ]
