# Generated by Django 3.0.7 on 2020-09-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_auto_20200922_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissions',
            name='active',
        ),
        migrations.RemoveField(
            model_name='emissions',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='emissions',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='emissions',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='requester',
            name='active',
        ),
        migrations.RemoveField(
            model_name='requester',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='requester',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='requester',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='roadload',
            name='active',
        ),
        migrations.RemoveField(
            model_name='roadload',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='roadload',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='roadload',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='soaktag',
            name='active',
        ),
        migrations.RemoveField(
            model_name='soaktag',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='soaktag',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='soaktag',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='active',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='updated',
        ),
        migrations.AddField(
            model_name='datahandler',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Entry soft-delete date'),
        ),
        migrations.AddField(
            model_name='datahandler',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=50, verbose_name='User who deleted the entry'),
        ),
        migrations.AddField(
            model_name='datahandler',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='emissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='backend.Emissions'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='backend.Requester'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='road_load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_load', to='backend.RoadLoad'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='soak_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soak_tag', to='backend.SoakTag'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='vehicle_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_info', to='backend.VehicleInfo'),
        ),
        migrations.AlterField(
            model_name='roadload',
            name='dyno_roll',
            field=models.CharField(choices=[('FWD', 'Fwd'), ('RWD', 'Rwd'), ('4WD', 'Awd'), ('', 'None')], default='', max_length=3, verbose_name='Dyno roll configuration'),
        ),
    ]
