# Generated by Django 3.0.7 on 2020-09-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20200924_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroadload',
            name='wheelbase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Wheelbase size'),
        ),
        migrations.AlterField(
            model_name='roadload',
            name='wheelbase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Wheelbase size'),
        ),
    ]
