# Generated by Django 3.0.7 on 2020-10-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_auto_20200928_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandler',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('USM', 'US Metric'), ('EU', 'EU'), ('GTR', 'GTR 15'), ('JPN', 'Japan 1015'), ('JC08', 'Japan JC08'), ('None', 'None')], default='', max_length=10, verbose_name='Country selection'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='test_mass_eu',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, verbose_name='Test mass (EU/COC)'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='transmission',
            field=models.CharField(blank=True, max_length=20, verbose_name='Transmission type'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('USM', 'US Metric'), ('EU', 'EU'), ('GTR', 'GTR 15'), ('JPN', 'Japan 1015'), ('JC08', 'Japan JC08'), ('None', 'None')], default='', max_length=10, verbose_name='Country selection'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='test_mass_eu',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, verbose_name='Test mass (EU/COC)'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='transmission',
            field=models.CharField(blank=True, max_length=20, verbose_name='Transmission type'),
        ),
    ]
