# Generated by Django 3.0.7 on 2020-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_auto_20201014_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandler',
            name='coastdown',
            field=models.CharField(choices=[('PROCEDURE', 'Yes, procedure attached'), ('DELIVERED', 'Yes, as delivered'), ('NO', 'No'), ('NONE', 'None')], default='None', max_length=20, verbose_name='Coastdown mode?'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('USM', 'US Metric'), ('EU', 'EU'), ('GTR', 'GTR 15'), ('JPN', 'Japan 1015'), ('JC08', 'Japan JC08'), ('NONE', 'None')], default='', max_length=10, verbose_name='Country selection'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='dyno_mode',
            field=models.CharField(blank=True, choices=[('PROCEDURE', 'Yes, procedure attached'), ('DELIVERED', 'Yes, as delivered'), ('NO', 'No'), ('NONE', 'None')], default='No', max_length=20, verbose_name='Dyno mode?'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='dyno_roll',
            field=models.CharField(choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('AWD', '4WD'), ('NONE', '')], default='', max_length=3, verbose_name='Dyno roll configuration'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='front_hooks',
            field=models.CharField(blank=True, choices=[('DRIVER', 'Yes - Driver Side'), ('PASSENGER', 'Yes - Passenger Side'), ('BOTH', 'Yes - Both Sides'), ('YES', 'Yes'), ('NO', 'No'), ('NONE', 'None')], default='None', max_length=10, verbose_name='Front tow hooks?'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='rear_hooks',
            field=models.CharField(blank=True, choices=[('DRIVER', 'Yes - Driver Side'), ('PASSENGER', 'Yes - Passenger Side'), ('BOTH', 'Yes - Both Sides'), ('YES', 'Yes'), ('NO', 'No'), ('NONE', 'None')], default='None', max_length=10, verbose_name='Rear tow hooks?'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='regulation',
            field=models.CharField(blank=True, choices=[('86', 'CFR 86'), ('1066', 'CFR 1066'), ('E3', 'Euro 3 (2000'), ('E4', 'Euro 4 (2005)'), ('E5', 'Euro 5 (2009)'), ('E6b', 'Euro 6b (2014)'), ('E6c', 'Euro 6c'), ('E6d_T', 'Euro 6d TEMP (2017)'), ('E6d', 'Euro 6d (2020)'), ('NONE', 'None')], max_length=10, verbose_name='Regulation'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMIT', 'Submitted'), ('REJECT', 'Rejected'), ('PENDING', 'Pending Changes'), ('APPROVE', 'Approved')], default='SUBMIT', max_length=10, null=True, verbose_name='Current status of the vehicle entry'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='veh_type',
            field=models.CharField(blank=True, choices=[('ICE', 'ICE'), ('HEV_48', 'HEV (48V)'), ('HEV', 'HEV'), ('PHEV', 'PHEV'), ('BEV', 'BEV'), ('NONE', 'None')], default='None', max_length=10, verbose_name='Vehicle type'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='coastdown',
            field=models.CharField(choices=[('PROCEDURE', 'Yes, procedure attached'), ('DELIVERED', 'Yes, as delivered'), ('NO', 'No'), ('NONE', 'None')], default='None', max_length=20, verbose_name='Coastdown mode?'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('USM', 'US Metric'), ('EU', 'EU'), ('GTR', 'GTR 15'), ('JPN', 'Japan 1015'), ('JC08', 'Japan JC08'), ('NONE', 'None')], default='', max_length=10, verbose_name='Country selection'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='dyno_mode',
            field=models.CharField(blank=True, choices=[('PROCEDURE', 'Yes, procedure attached'), ('DELIVERED', 'Yes, as delivered'), ('NO', 'No'), ('NONE', 'None')], default='No', max_length=20, verbose_name='Dyno mode?'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='dyno_roll',
            field=models.CharField(choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('AWD', '4WD'), ('NONE', '')], default='', max_length=3, verbose_name='Dyno roll configuration'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='front_hooks',
            field=models.CharField(blank=True, choices=[('DRIVER', 'Yes - Driver Side'), ('PASSENGER', 'Yes - Passenger Side'), ('BOTH', 'Yes - Both Sides'), ('YES', 'Yes'), ('NO', 'No'), ('NONE', 'None')], default='None', max_length=10, verbose_name='Front tow hooks?'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='rear_hooks',
            field=models.CharField(blank=True, choices=[('DRIVER', 'Yes - Driver Side'), ('PASSENGER', 'Yes - Passenger Side'), ('BOTH', 'Yes - Both Sides'), ('YES', 'Yes'), ('NO', 'No'), ('NONE', 'None')], default='None', max_length=10, verbose_name='Rear tow hooks?'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='regulation',
            field=models.CharField(blank=True, choices=[('86', 'CFR 86'), ('1066', 'CFR 1066'), ('E3', 'Euro 3 (2000'), ('E4', 'Euro 4 (2005)'), ('E5', 'Euro 5 (2009)'), ('E6b', 'Euro 6b (2014)'), ('E6c', 'Euro 6c'), ('E6d_T', 'Euro 6d TEMP (2017)'), ('E6d', 'Euro 6d (2020)'), ('NONE', 'None')], max_length=10, verbose_name='Regulation'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMIT', 'Submitted'), ('REJECT', 'Rejected'), ('PENDING', 'Pending Changes'), ('APPROVE', 'Approved')], default='SUBMIT', max_length=10, null=True, verbose_name='Current status of the vehicle entry'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='veh_type',
            field=models.CharField(blank=True, choices=[('ICE', 'ICE'), ('HEV_48', 'HEV (48V)'), ('HEV', 'HEV'), ('PHEV', 'PHEV'), ('BEV', 'BEV'), ('NONE', 'None')], default='None', max_length=10, verbose_name='Vehicle type'),
        ),
    ]
