# Generated by Django 3.0.7 on 2020-10-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_auto_20201021_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandler',
            name='cscm',
            field=models.CharField(blank=True, max_length=10, verbose_name='CSCm Distance'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='regulation',
            field=models.CharField(blank=True, choices=[('86', 'CFR86'), ('1066', 'CFR1066'), ('E3', 'Euro 3 (2000)'), ('E4', 'Euro 4 (2005)'), ('E5', 'Euro 5 (2009)'), ('E6b', 'Euro 6b (2014)'), ('E6c', 'Euro 6c'), ('E6d_T', 'Euro 6d TEMP (2017)'), ('E6d', 'Euro 6d (2020)'), ('NONE', 'None')], max_length=10, verbose_name='Regulation'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='cscm',
            field=models.CharField(blank=True, max_length=10, verbose_name='CSCm Distance'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='regulation',
            field=models.CharField(blank=True, choices=[('86', 'CFR86'), ('1066', 'CFR1066'), ('E3', 'Euro 3 (2000)'), ('E4', 'Euro 4 (2005)'), ('E5', 'Euro 5 (2009)'), ('E6b', 'Euro 6b (2014)'), ('E6c', 'Euro 6c'), ('E6d_T', 'Euro 6d TEMP (2017)'), ('E6d', 'Euro 6d (2020)'), ('NONE', 'None')], max_length=10, verbose_name='Regulation'),
        ),
    ]
