# Generated by Django 3.0.7 on 2020-10-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_auto_20201022_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandler',
            name='mass_usa',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mass (EPA)'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='mass_usa',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mass (EPA)'),
        ),
    ]
