# Generated by Django 3.0.7 on 2020-10-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_auto_20201022_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandler',
            name='all_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='All-electric range'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='charge_num',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complete project/charge #'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='marmon_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Dual flange distance'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='nom_bat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Nominal battery voltage'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMIT', 'Submitted'), ('PENDING', 'Pending changes'), ('REJECTED', 'Rejected'), ('APPROVE', 'Approved'), ('ARCHIVE', 'Archived'), ('DRAFT', 'Draft')], default='SUBMIT', max_length=10, null=True, verbose_name='Current status of the vehicle entry'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='usable_bat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Usable battery energy'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='all_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='All-electric range'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='charge_num',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complete project/charge #'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='marmon_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Dual flange distance'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='nom_bat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Nominal battery voltage'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMIT', 'Submitted'), ('PENDING', 'Pending changes'), ('REJECTED', 'Rejected'), ('APPROVE', 'Approved'), ('ARCHIVE', 'Archived'), ('DRAFT', 'Draft')], default='SUBMIT', max_length=10, null=True, verbose_name='Current status of the vehicle entry'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='usable_bat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Usable battery energy'),
        ),
    ]
