# Generated by Django 3.0.7 on 2020-10-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_auto_20201023_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahandler',
            name='spreadsheet',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='historicaldatahandler',
            name='spreadsheet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='test_name',
            field=models.CharField(max_length=100, verbose_name='Test Vehicle Naming'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='test_name',
            field=models.CharField(max_length=100, verbose_name='Test Vehicle Naming'),
        ),
    ]
