# Generated by Django 3.0.7 on 2020-11-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_auto_20201023_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datahandler',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='historicaldatahandler',
            name='upload',
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='desc',
            field=models.CharField(blank=True, max_length=512, verbose_name='Additional notes'),
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('BEV', 'BEV'), ('CARBLEVIIIE10Prem', 'CARB LEV III E10 - Premium'), ('CARBLEVIIIE10Reg', 'CARB LEV III E10 - Regular'), ('China6E0Prem', 'China6 E0 - Premium'), ('EPADiesel2D', 'EPA Diesel 2D'), ('EPATier2E0Prem', 'EPA Tier 2 E0 - Premium'), ('EPATier2E0RegCold', 'EPA Tier 2 E0 - Regular Cold'), ('EPATier3E10Prem', 'EPA Tier 3 E10 - Premium'), ('EPATier3E10PremCold', 'EPA Tier 3 E10 - Premium Cold'), ('EPATier3E10Reg', 'EPA Tier 3 E10 - Regular'), ('EPATier3E10RegCold', 'EPA Tier 3 E10 - Regular Cold'), ('Euro6E10Prem', 'Euro6 E10 - Premium'), ('PumpE10Prem', 'Pump E10 - Premium'), ('PumpE10Reg', 'Pump E10 - Regular'), ('Hydrogen', 'Hydrogen'), ('Other', 'Other (Please Specify)'), ('NONE', 'None')], max_length=50, verbose_name='VDC fuel type'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='desc',
            field=models.CharField(blank=True, max_length=512, verbose_name='Additional notes'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('BEV', 'BEV'), ('CARBLEVIIIE10Prem', 'CARB LEV III E10 - Premium'), ('CARBLEVIIIE10Reg', 'CARB LEV III E10 - Regular'), ('China6E0Prem', 'China6 E0 - Premium'), ('EPADiesel2D', 'EPA Diesel 2D'), ('EPATier2E0Prem', 'EPA Tier 2 E0 - Premium'), ('EPATier2E0RegCold', 'EPA Tier 2 E0 - Regular Cold'), ('EPATier3E10Prem', 'EPA Tier 3 E10 - Premium'), ('EPATier3E10PremCold', 'EPA Tier 3 E10 - Premium Cold'), ('EPATier3E10Reg', 'EPA Tier 3 E10 - Regular'), ('EPATier3E10RegCold', 'EPA Tier 3 E10 - Regular Cold'), ('Euro6E10Prem', 'Euro6 E10 - Premium'), ('PumpE10Prem', 'Pump E10 - Premium'), ('PumpE10Reg', 'Pump E10 - Regular'), ('Hydrogen', 'Hydrogen'), ('Other', 'Other (Please Specify)'), ('NONE', 'None')], max_length=50, verbose_name='VDC fuel type'),
        ),
    ]
