# Generated by Django 3.0.7 on 2021-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_auto_20201210_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldchoices',
            name='display_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfieldchoices',
            name='display_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datahandler',
            name='spreadsheet',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='historicaldatahandler',
            name='spreadsheet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
