# Generated by Django 3.0.7 on 2021-01-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_auto_20210105_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldchoices',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='historicalfieldchoices',
            name='display_name',
        ),
    ]
