# Generated by Django 3.0.7 on 2021-01-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_auto_20210105_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=255, verbose_name='Error message to be returned to the user')),
            ],
        ),
    ]
