# Generated by Django 3.0.7 on 2021-01-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_errorcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcodes',
            name='location',
            field=models.CharField(default=None, max_length=50, verbose_name='Associated class or function where the error happens'),
            preserve_default=False,
        ),
    ]
