# Generated by Django 3.1.5 on 2021-04-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_auto_20210405_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltests',
            name='test_name',
            field=models.CharField(default='Test Name', max_length=100, verbose_name='Reference name for the test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tests',
            name='test_name',
            field=models.CharField(default='Test Name', max_length=100, verbose_name='Reference name for the test'),
            preserve_default=False,
        ),
    ]
